spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass

app.sql.registrations.insert=insert into registrations (classes_id, students_id) values (?, ?)
app.sql.registrations.find-by-id=select cl.id classId, cs.id courseId, cs.name courseName, cs.fees fees, cl.start_date startAt, st.id studentId, st.name studentName, st.phone phone, st.email email from registrations rg join classes cl on rg.classes_id = cl.id join courses cs on cs.id = cl.course_id join students st on rg.students_id = st.id where cl.id = ? and st.id = ?
app.sql.registrations.search=select cl.id classId, cs.id courseId, cs.name courseName, cs.fees fees, cl.start_date startAt, st.id studentId, st.name studentName, st.phone phone, st.email email from registrations rg join classes cl on rg.classes_id = cl.id join courses cs on cs.id = cl.course_id join students st on rg.students_id = st.id where 1 = 1
app.sql.registrations.delete=delete from registrations where classes_id = ? and students_id = ?

app.sql.class.find-by-id=select cl.id id, cs.id courseId, cs.name courseName, cl.start_date startDate, cs.fees fees, cl.months months, count(rg.students_id) students from classes cl join courses cs on cl.course_id = cs.id join registrations rg on cl.id = rg.classes_id where cl.id = ? group by cl.id

app.sql.student.find-by-id=select st.id id, st.name name, st.phone phone, st.email email, count(rg.classes_id) registrations from students st join registrations rg on st.id = rg.students_id where st.id = ? group by st.id

app.sql.course.insert=insert into courses (name, hours, fees, description) values (?, ?, ?, ?)
app.sql.course.count-by-name=select count(id) from courses where name = ?
app.sql.course.find-by-id=select cs.id, cs.name, cs.fees, cs.hours, cs.description, count(cl.id) as classes from courses cs left join classes cl on cs.id = cl.course_id where cs.id = ? group by cs.id, cs.name, cs.fees, cs.hours, cs.description
app.sql.course.search=select * from courses where 1 = 1