spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass

spring.sql.init.mode=always

app.sql.registrations.insert=insert into registrations (classes_id, students_id) values (?, ?)
app.sql.registrations.find-by-id=select cl.id classId, cs.id courseId, cs.name courseName, cs.fees fees, cl.start_date startAt, st.id studentId, st.name studentName, st.phone phone, st.email email from registrations rg join classes cl on rg.classes_id = cl.id join courses cs on cs.id = cl.course_id join students st on rg.students_id = st.id where cl.id = ? and st.id = ?