services:
  db:
    image: mysql:9.6
    container_name: ep16_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  dbdata: