spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass

app.sql.course.count-by-name=select count(id) from courses where name = ?
app.sql.course.find-by-id=select cs.id, cs.name, cs.fees, cs.hours, cs.description, count(cl.id) as classes from courses cs left join classes cl on cs.id = cl.course_id where cs.id = ? group by cs.id, cs.name, cs.fees, cs.hours, cs.description
app.sql.course.search=select * from courses where 1 = 1
app.sql.course.update=update courses set %s where id = ?
app.sql.course.delete=delete from courses where id = ?

app.sql.student.count-by-email=select count(id) from students where email = :email
app.sql.student.find-by-id=select s.id, s.name, s.phone, s.email, count(r.students_id) registrations from students s \
	left join registrations r on s.id = r.students_id \
	where s.id = :id \
	group by s.id, s.name, s.phone, s.email
app.sql.student.update=update students set %s where id = :id
app.sql.student.delete=delete from students where id = :id
app.sql.student.search=select * from students where 1 = 1

app.sql.student.insert=insert into students(name, phone, email) values (:name, :phone, :email)

app.sql.class.count-by-course=select count(course_id) from classes where course_id = ? 

app.sql.registrations.count-by-student=select count(students_id) from registrations where students_id = :studentId