spring.application.name=ep17-programmatic-trx

app.sql.account.find-by-code=select code, name, amount from account where code = :code
app.sql.transaction-seq.find-by-id=select * from transaction_seq where trx_date = :id
app.sql.transaction-seq.create=insert into transaction_seq (trx_date, seq_num) values (:trxDate, :seqNum)
app.sql.transaction-seq.update=update transaction_seq set seq_num = :seqNum where trx_date = :trxDate