spring.application.name=ep17-programmatic-trx

app.sql.account.find-by-code=select code, name, amount from account where code = :code
app.sql.transaction-seq.find-by-id=select * from transaction_seq where trx_date = :id
app.sql.transaction-seq.create=insert into transaction_seq (trx_date, seq_num) values (:trxDate, :seqNum)
app.sql.transaction-seq.update=update transaction_seq set seq_num = :seqNum where trx_date = :trxDate

app.sql.transaction.create=insert into transaction (trx_id, trx_type, issuer, amount, remark, issue_at) \
	values (:trxId, :trxType, :issuer, :amount, :remark, :issueAt)
app.sql.transfer.create=insert into transaction_transfer (trx_id, receiver) values (:trxId, :receiver)
app.sql.account.update=update account set amount = :amount where code = :code

app.limit.min-balance=500