spring.application.name=ep37-rest-security

app.setting.otp.otp-life=3
app.setting.otp.opt-limit-duration=3
app.setting.otp.otp-limit-count=3

app.jwt.token.issuer=com.jdc.security
app.jwt.token.access-life=1
app.jwt.token.refresh-life=3

app.admin.user.name=Administrator
app.admin.user.email=admin@example.com
app.admin.user.password=${ADMIN_USER_PASS:password}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=http://productdb:5432/productdb
spring.datasource.username=productdb
spring.datasource.password=${POSTGRES_PASS:password}

spring.mail.host=mailhog
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
