DROP TABLE IF EXISTS account;

CREATE TABLE account (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) primary key,
	name varchar(40),
	phone varchar(40),
	email varchar(40)
);