spring.application.name=ep16-spring-transaction

spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass

app.sale-price-rate=10
app.tax-rate=5

app.sql.employee.is-present=select count(id) from employee where id = :id

app.sql.supplier.is-present=select count(id) from supplier where id = :id

app.sql.product.is-present=select count(id) from product where id = :id

app.sql.product-supplier.is-present=select count(*) from product_supplier \
	where product_id = :productId and supplier_id = :supplierId
app.sql.product-supplier.create=insert into product_supplier(product_id, supplier_id) \
	values (:productId, :supplierId)
	
app.sql.purchase-product.create=insert into purchase_product(product_id, version, purchase_id, unit_price, quantity) \
	values (:productId, :version, :purchaseId, :unitPrice, :quantity)
	
app.sql.purchase.create=insert into purchase(employee_id, supplier_id, purchase_date, transport_fee) \
	values (:employeeId, :supplierId, :purchaseDate, :transportationFees)

app.sql.stock.find-by-id=select * from stock where product_id = :productId
app.sql.stock.update=update stock set version = :version, sale_price = :salePrice, purchase_price = :purchasePrice \
	stock_amount = :amount where product_id = :productId
	
app.sql.stock-history.create=insert into stock_history (product_id, verion, action_type, sale_price, purchase_price, amount) \
	values (:productId, :version, :actionType, :salePrice, :purchasePrice, :amount)
