spring.application.name=ep24-handler-method-args

app.sql.state.find-all=select id, name from state
app.sql.state.find-by-id=select * from state where id = :id

app.sql.state.search=select * from state where 1 = 1