DROP TABLE IF EXISTS account;

CREATE TABLE account (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) primary key,
	name varchar(40),
	phone varchar(40),
	email varchar(40)
);

insert into account (name, phone, email) values ('user1', 'phone1', 'email1');
insert into account (name, phone, email) values ('user2', 'phone2', 'email2');
insert into account (name, phone, email) values ('user3', 'phone3', 'email3');